### ISSUE TITLE
参考Demo 在Notify的时候报错

### ISSUE THREAD

**Issue by holin** [jasl/tenpay_demo#1]
ArgumentError (wrong number of arguments (2 for 1))

这一行：
    if JaslTenpay::Notify.verify? params.except(*request.path_parameters.keys), verify_trade_state: true

**Comment by holin** [comment]
去掉后面的 , verify_trade_state: true，回调成功。

 verify_trade_state: true 是干嘛用的？

**Comment by jasl** [comment]
我去 这么多年我才注意到这边还有个 issue。。。
